# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          optimize: svg
          experimental_features: --optimize-svg
          user: neandreev
          template: classic
          base: header, activity, community
          config_display: columns
          config_timezone: Asia/Yekaterinburg
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 6
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music_provider: lastfm
          plugin_music_mode: recent
          plugin_music_user: neandreev
          plugin_music: yes
          plugin_wakatime: yes
          plugin_wakatime_token: 7d9efcdb-9862-4762-ad53-109476996745
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: time, projects, projects-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: neandreev
